// AUTO-GENERATED by scripts/gen-cbu-fixture.mjs from documents/CBU_docx/CBU_Margin_Input/CBU-AC0084_DDP_VN_MARGIN_INPUT.md
// Do NOT edit by hand and do NOT adjust numbers to make a test pass — the markdown is the source of truth.
// Column note: the md prints "Total (col) = Σ qty × value" for per-unit columns (bank fee, logistics, ...),
// so `totals` below are Σ qty × per-unit value, as in the Excel TOTAL row.

export interface Ac0084Row {
  lineNo: number; partNo: string; qty: number;
  /** Excel col F — TOTAL weight of the line, in pounds. */
  totalWeightLb: number;
  /** Excel col G — weight per unit, kg. */
  weightKg: number;
  /** Excel col H — supplier price per unit, USD. */
  materialUsd: number;
  /** Excel col I — percent (0 = 0%). */
  dutyPct: number;
  expected: {
    bankFeeUsd: number; logisticsUsd: number; dutyUsd: number; commissionUsd: number; citUsd: number;
    unitCostUsd: number; ddpPriceUsd: number; ddpPriceVnd: number; totalRevenueVnd: number;
    marginPerUnitUsd: number; marginPct: number; totalMarginUsd: number; totalCostUsd: number;
  };
}

/** Pricing parameters (md §2), percent numbers (25 = 25%). */
export const AC0084_PARAMS = {
  fx: 26500, targetMarginPct: 25, commissionPct: 3, citPct: 20,
  pctFinanced: 50, interestPct: 15, financingDays: 15, daysPerYear: 360,
  vndRoundingStep: 10000, lbToKg: 0.4536,
  goodsOrigin: "Oversea", destinationCountry: "VN",
  insurance: { insuredValuePct: 110, ratePct: 0.01, minUsd: 15 },
  bank: { remitRatePct: 0.2, remitVatFactor: 1.1, minRemitUsd: 50, receiveRatePct: 0.05, receiveVatFactor: 1, minReceiveUsd: 5, receiveBaseUsd: 0, otherUsd: 0 },
} as const;

/** Logistic sheet (md §6). */
export const AC0084_LOGISTICS = {
  air: { freightFixedUsd: 500, freightRatePerKg: 2.5, chargeableKg: 1300, clearanceUsd: 150, inlandUsd: 100, expectedFreightUsd: 3750, expectedInsuranceUsd: 15, expectedPoolUsd: 4015 },
  sea: { freightFixedUsd: 800, freightRatePerKg: 0, chargeableKg: 0, clearanceUsd: 150, inlandUsd: 100, expectedFreightUsd: 800, expectedInsuranceUsd: 15, expectedPoolUsd: 1065 },
} as const;

/** Bank Fee sheet total (md §7): remittance 50.00 + receive 0 (Country = VN) + other 0. */
export const AC0084_EXPECTED_BANK_TOTAL_USD = 50;

export const AC0084_AIR: Ac0084Row[] = [
  {
    "lineNo": 1,
    "partNo": "A23-170",
    "qty": 320,
    "totalWeightLb": 121.6,
    "weightKg": 0.1724,
    "materialUsd": 4.37,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.025,
      "logisticsUsd": 0.6712,
      "dutyUsd": 0,
      "commissionUsd": 0.213,
      "citUsd": 0.0426,
      "unitCostUsd": 5.3218,
      "ddpPriceUsd": 7.1,
      "ddpPriceVnd": 190000,
      "totalRevenueVnd": 60800000,
      "marginPerUnitUsd": 1.78,
      "marginPct": 25.04,
      "totalMarginUsd": 569,
      "totalCostUsd": 1703
    }
  },
  {
    "lineNo": 2,
    "partNo": "A23-170-B",
    "qty": 160,
    "totalWeightLb": 67.2,
    "weightKg": 0.1905,
    "materialUsd": 4.68,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0268,
      "logisticsUsd": 0.7419,
      "dutyUsd": 0,
      "commissionUsd": 0.2292,
      "citUsd": 0.0458,
      "unitCostUsd": 5.7237,
      "ddpPriceUsd": 7.64,
      "ddpPriceVnd": 210000,
      "totalRevenueVnd": 33600000,
      "marginPerUnitUsd": 1.92,
      "marginPct": 25.08,
      "totalMarginUsd": 307,
      "totalCostUsd": 916
    }
  },
  {
    "lineNo": 3,
    "partNo": "A23-186",
    "qty": 320,
    "totalWeightLb": 102.4,
    "weightKg": 0.1452,
    "materialUsd": 4.81,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0275,
      "logisticsUsd": 0.5652,
      "dutyUsd": 0,
      "commissionUsd": 0.2271,
      "citUsd": 0.0454,
      "unitCostUsd": 5.6753,
      "ddpPriceUsd": 7.57,
      "ddpPriceVnd": 210000,
      "totalRevenueVnd": 67200000,
      "marginPerUnitUsd": 1.89,
      "marginPct": 25.03,
      "totalMarginUsd": 606,
      "totalCostUsd": 1816
    }
  },
  {
    "lineNo": 4,
    "partNo": "A23-186-B",
    "qty": 160,
    "totalWeightLb": 148,
    "weightKg": 0.4196,
    "materialUsd": 5.19,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0297,
      "logisticsUsd": 1.6339,
      "dutyUsd": 0,
      "commissionUsd": 0.288,
      "citUsd": 0.0576,
      "unitCostUsd": 7.1992,
      "ddpPriceUsd": 9.6,
      "ddpPriceVnd": 260000,
      "totalRevenueVnd": 41600000,
      "marginPerUnitUsd": 2.4,
      "marginPct": 25.01,
      "totalMarginUsd": 384,
      "totalCostUsd": 1152
    }
  },
  {
    "lineNo": 5,
    "partNo": "A23-172",
    "qty": 400,
    "totalWeightLb": 148,
    "weightKg": 0.1678,
    "materialUsd": 4.37,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.025,
      "logisticsUsd": 0.6536,
      "dutyUsd": 0,
      "commissionUsd": 0.2124,
      "citUsd": 0.0425,
      "unitCostUsd": 5.3034,
      "ddpPriceUsd": 7.08,
      "ddpPriceVnd": 190000,
      "totalRevenueVnd": 76000000,
      "marginPerUnitUsd": 1.78,
      "marginPct": 25.09,
      "totalMarginUsd": 711,
      "totalCostUsd": 2121
    }
  },
  {
    "lineNo": 6,
    "partNo": "A23-172-B",
    "qty": 200,
    "totalWeightLb": 185,
    "weightKg": 0.4196,
    "materialUsd": 4.68,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0268,
      "logisticsUsd": 1.6339,
      "dutyUsd": 0,
      "commissionUsd": 0.2667,
      "citUsd": 0.0533,
      "unitCostUsd": 6.6607,
      "ddpPriceUsd": 8.89,
      "ddpPriceVnd": 240000,
      "totalRevenueVnd": 48000000,
      "marginPerUnitUsd": 2.23,
      "marginPct": 25.08,
      "totalMarginUsd": 446,
      "totalCostUsd": 1332
    }
  },
  {
    "lineNo": 7,
    "partNo": "A23-171",
    "qty": 400,
    "totalWeightLb": 304,
    "weightKg": 0.3447,
    "materialUsd": 4.37,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.025,
      "logisticsUsd": 1.3425,
      "dutyUsd": 0,
      "commissionUsd": 0.2412,
      "citUsd": 0.0482,
      "unitCostUsd": 6.0269,
      "ddpPriceUsd": 8.04,
      "ddpPriceVnd": 220000,
      "totalRevenueVnd": 88000000,
      "marginPerUnitUsd": 2.01,
      "marginPct": 25.04,
      "totalMarginUsd": 805,
      "totalCostUsd": 2411
    }
  },
  {
    "lineNo": 8,
    "partNo": "A23-171-B",
    "qty": 200,
    "totalWeightLb": 150,
    "weightKg": 0.3402,
    "materialUsd": 4.68,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0268,
      "logisticsUsd": 1.3248,
      "dutyUsd": 0,
      "commissionUsd": 0.2535,
      "citUsd": 0.0507,
      "unitCostUsd": 6.3358,
      "ddpPriceUsd": 8.45,
      "ddpPriceVnd": 230000,
      "totalRevenueVnd": 46000000,
      "marginPerUnitUsd": 2.11,
      "marginPct": 25.02,
      "totalMarginUsd": 423,
      "totalCostUsd": 1267
    }
  },
  {
    "lineNo": 9,
    "partNo": "A23-173",
    "qty": 400,
    "totalWeightLb": 248,
    "weightKg": 0.2812,
    "materialUsd": 4.55,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.026,
      "logisticsUsd": 1.0952,
      "dutyUsd": 0,
      "commissionUsd": 0.2385,
      "citUsd": 0.0477,
      "unitCostUsd": 5.9574,
      "ddpPriceUsd": 7.95,
      "ddpPriceVnd": 220000,
      "totalRevenueVnd": 88000000,
      "marginPerUnitUsd": 1.99,
      "marginPct": 25.06,
      "totalMarginUsd": 797,
      "totalCostUsd": 2383
    }
  },
  {
    "lineNo": 10,
    "partNo": "A23-173-B",
    "qty": 200,
    "totalWeightLb": 128,
    "weightKg": 0.2903,
    "materialUsd": 4.73,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0271,
      "logisticsUsd": 1.1305,
      "dutyUsd": 0,
      "commissionUsd": 0.2475,
      "citUsd": 0.0495,
      "unitCostUsd": 6.1845,
      "ddpPriceUsd": 8.25,
      "ddpPriceVnd": 220000,
      "totalRevenueVnd": 44000000,
      "marginPerUnitUsd": 2.07,
      "marginPct": 25.04,
      "totalMarginUsd": 413,
      "totalCostUsd": 1237
    }
  },
  {
    "lineNo": 11,
    "partNo": "A23-180",
    "qty": 400,
    "totalWeightLb": 212,
    "weightKg": 0.2404,
    "materialUsd": 4.87,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0279,
      "logisticsUsd": 0.9362,
      "dutyUsd": 0,
      "commissionUsd": 0.2454,
      "citUsd": 0.0491,
      "unitCostUsd": 6.1285,
      "ddpPriceUsd": 8.18,
      "ddpPriceVnd": 220000,
      "totalRevenueVnd": 88000000,
      "marginPerUnitUsd": 2.05,
      "marginPct": 25.08,
      "totalMarginUsd": 821,
      "totalCostUsd": 2451
    }
  },
  {
    "lineNo": 12,
    "partNo": "A23-180-B",
    "qty": 200,
    "totalWeightLb": 102,
    "weightKg": 0.2313,
    "materialUsd": 6.46,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0369,
      "logisticsUsd": 0.9009,
      "dutyUsd": 0,
      "commissionUsd": 0.3111,
      "citUsd": 0.0622,
      "unitCostUsd": 7.7711,
      "ddpPriceUsd": 10.37,
      "ddpPriceVnd": 280000,
      "totalRevenueVnd": 56000000,
      "marginPerUnitUsd": 2.6,
      "marginPct": 25.06,
      "totalMarginUsd": 520,
      "totalCostUsd": 1554
    }
  },
  {
    "lineNo": 13,
    "partNo": "A23-169",
    "qty": 240,
    "totalWeightLb": 153.6,
    "weightKg": 0.2903,
    "materialUsd": 4.87,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0279,
      "logisticsUsd": 1.1305,
      "dutyUsd": 0,
      "commissionUsd": 0.2535,
      "citUsd": 0.0507,
      "unitCostUsd": 6.3325,
      "ddpPriceUsd": 8.45,
      "ddpPriceVnd": 230000,
      "totalRevenueVnd": 55200000,
      "marginPerUnitUsd": 2.12,
      "marginPct": 25.06,
      "totalMarginUsd": 508,
      "totalCostUsd": 1520
    }
  },
  {
    "lineNo": 14,
    "partNo": "A23-169-B",
    "qty": 120,
    "totalWeightLb": 76.8,
    "weightKg": 0.2903,
    "materialUsd": 5.01,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0287,
      "logisticsUsd": 1.1305,
      "dutyUsd": 0,
      "commissionUsd": 0.2595,
      "citUsd": 0.0519,
      "unitCostUsd": 6.4805,
      "ddpPriceUsd": 8.65,
      "ddpPriceVnd": 230000,
      "totalRevenueVnd": 27600000,
      "marginPerUnitUsd": 2.17,
      "marginPct": 25.08,
      "totalMarginUsd": 260,
      "totalCostUsd": 778
    }
  },
  {
    "lineNo": 15,
    "partNo": "A23-170",
    "qty": 240,
    "totalWeightLb": 76,
    "weightKg": 0.1436,
    "materialUsd": 4.37,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.025,
      "logisticsUsd": 0.5594,
      "dutyUsd": 0,
      "commissionUsd": 0.2082,
      "citUsd": 0.0416,
      "unitCostUsd": 5.2042,
      "ddpPriceUsd": 6.94,
      "ddpPriceVnd": 190000,
      "totalRevenueVnd": 45600000,
      "marginPerUnitUsd": 1.74,
      "marginPct": 25.01,
      "totalMarginUsd": 417,
      "totalCostUsd": 1249
    }
  },
  {
    "lineNo": 16,
    "partNo": "A23-170-B",
    "qty": 120,
    "totalWeightLb": 50.4,
    "weightKg": 0.1905,
    "materialUsd": 4.68,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0268,
      "logisticsUsd": 0.7419,
      "dutyUsd": 0,
      "commissionUsd": 0.2292,
      "citUsd": 0.0458,
      "unitCostUsd": 5.7237,
      "ddpPriceUsd": 7.64,
      "ddpPriceVnd": 210000,
      "totalRevenueVnd": 25200000,
      "marginPerUnitUsd": 1.92,
      "marginPct": 25.08,
      "totalMarginUsd": 230,
      "totalCostUsd": 687
    }
  }
];

export const AC0084_SEA: Ac0084Row[] = [
  {
    "lineNo": 1,
    "partNo": "A23-170",
    "qty": 320,
    "totalWeightLb": 121.6,
    "weightKg": 0.1724,
    "materialUsd": 4.37,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.025,
      "logisticsUsd": 0.178,
      "dutyUsd": 0,
      "commissionUsd": 0.1923,
      "citUsd": 0.0385,
      "unitCostUsd": 4.8038,
      "ddpPriceUsd": 6.41,
      "ddpPriceVnd": 170000,
      "totalRevenueVnd": 54400000,
      "marginPerUnitUsd": 1.61,
      "marginPct": 25.06,
      "totalMarginUsd": 514,
      "totalCostUsd": 1537
    }
  },
  {
    "lineNo": 2,
    "partNo": "A23-170-B",
    "qty": 160,
    "totalWeightLb": 67.2,
    "weightKg": 0.1905,
    "materialUsd": 4.68,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0268,
      "logisticsUsd": 0.1968,
      "dutyUsd": 0,
      "commissionUsd": 0.2061,
      "citUsd": 0.0412,
      "unitCostUsd": 5.1509,
      "ddpPriceUsd": 6.87,
      "ddpPriceVnd": 190000,
      "totalRevenueVnd": 30400000,
      "marginPerUnitUsd": 1.72,
      "marginPct": 25.02,
      "totalMarginUsd": 275,
      "totalCostUsd": 824
    }
  },
  {
    "lineNo": 3,
    "partNo": "A23-186",
    "qty": 320,
    "totalWeightLb": 102.4,
    "weightKg": 0.1452,
    "materialUsd": 4.81,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0275,
      "logisticsUsd": 0.1499,
      "dutyUsd": 0,
      "commissionUsd": 0.2097,
      "citUsd": 0.0419,
      "unitCostUsd": 5.2391,
      "ddpPriceUsd": 6.99,
      "ddpPriceVnd": 190000,
      "totalRevenueVnd": 60800000,
      "marginPerUnitUsd": 1.75,
      "marginPct": 25.05,
      "totalMarginUsd": 560,
      "totalCostUsd": 1677
    }
  },
  {
    "lineNo": 4,
    "partNo": "A23-186-B",
    "qty": 160,
    "totalWeightLb": 148,
    "weightKg": 0.4196,
    "materialUsd": 5.19,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0297,
      "logisticsUsd": 0.4334,
      "dutyUsd": 0,
      "commissionUsd": 0.2376,
      "citUsd": 0.0475,
      "unitCostUsd": 5.9382,
      "ddpPriceUsd": 7.92,
      "ddpPriceVnd": 210000,
      "totalRevenueVnd": 33600000,
      "marginPerUnitUsd": 1.98,
      "marginPct": 25.02,
      "totalMarginUsd": 317,
      "totalCostUsd": 950
    }
  },
  {
    "lineNo": 5,
    "partNo": "A23-172",
    "qty": 400,
    "totalWeightLb": 148,
    "weightKg": 0.1678,
    "materialUsd": 4.37,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.025,
      "logisticsUsd": 0.1734,
      "dutyUsd": 0,
      "commissionUsd": 0.192,
      "citUsd": 0.0384,
      "unitCostUsd": 4.7988,
      "ddpPriceUsd": 6.4,
      "ddpPriceVnd": 170000,
      "totalRevenueVnd": 68000000,
      "marginPerUnitUsd": 1.6,
      "marginPct": 25.02,
      "totalMarginUsd": 640,
      "totalCostUsd": 1920
    }
  },
  {
    "lineNo": 6,
    "partNo": "A23-172-B",
    "qty": 200,
    "totalWeightLb": 185,
    "weightKg": 0.4196,
    "materialUsd": 4.68,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0268,
      "logisticsUsd": 0.4334,
      "dutyUsd": 0,
      "commissionUsd": 0.216,
      "citUsd": 0.0432,
      "unitCostUsd": 5.3994,
      "ddpPriceUsd": 7.2,
      "ddpPriceVnd": 200000,
      "totalRevenueVnd": 40000000,
      "marginPerUnitUsd": 1.8,
      "marginPct": 25.01,
      "totalMarginUsd": 360,
      "totalCostUsd": 1080
    }
  },
  {
    "lineNo": 7,
    "partNo": "A23-171",
    "qty": 400,
    "totalWeightLb": 304,
    "weightKg": 0.3447,
    "materialUsd": 4.37,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.025,
      "logisticsUsd": 0.3561,
      "dutyUsd": 0,
      "commissionUsd": 0.1998,
      "citUsd": 0.04,
      "unitCostUsd": 4.9908,
      "ddpPriceUsd": 6.66,
      "ddpPriceVnd": 180000,
      "totalRevenueVnd": 72000000,
      "marginPerUnitUsd": 1.67,
      "marginPct": 25.06,
      "totalMarginUsd": 668,
      "totalCostUsd": 1996
    }
  },
  {
    "lineNo": 8,
    "partNo": "A23-171-B",
    "qty": 200,
    "totalWeightLb": 150,
    "weightKg": 0.3402,
    "materialUsd": 4.68,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0268,
      "logisticsUsd": 0.3514,
      "dutyUsd": 0,
      "commissionUsd": 0.2127,
      "citUsd": 0.0425,
      "unitCostUsd": 5.3134,
      "ddpPriceUsd": 7.09,
      "ddpPriceVnd": 190000,
      "totalRevenueVnd": 38000000,
      "marginPerUnitUsd": 1.78,
      "marginPct": 25.06,
      "totalMarginUsd": 355,
      "totalCostUsd": 1063
    }
  },
  {
    "lineNo": 9,
    "partNo": "A23-173",
    "qty": 400,
    "totalWeightLb": 248,
    "weightKg": 0.2812,
    "materialUsd": 4.55,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.026,
      "logisticsUsd": 0.2905,
      "dutyUsd": 0,
      "commissionUsd": 0.2046,
      "citUsd": 0.0409,
      "unitCostUsd": 5.112,
      "ddpPriceUsd": 6.82,
      "ddpPriceVnd": 190000,
      "totalRevenueVnd": 76000000,
      "marginPerUnitUsd": 1.71,
      "marginPct": 25.04,
      "totalMarginUsd": 683,
      "totalCostUsd": 2045
    }
  },
  {
    "lineNo": 10,
    "partNo": "A23-173-B",
    "qty": 200,
    "totalWeightLb": 128,
    "weightKg": 0.2903,
    "materialUsd": 4.73,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0271,
      "logisticsUsd": 0.2999,
      "dutyUsd": 0,
      "commissionUsd": 0.2127,
      "citUsd": 0.0425,
      "unitCostUsd": 5.3122,
      "ddpPriceUsd": 7.09,
      "ddpPriceVnd": 190000,
      "totalRevenueVnd": 38000000,
      "marginPerUnitUsd": 1.78,
      "marginPct": 25.08,
      "totalMarginUsd": 356,
      "totalCostUsd": 1062
    }
  },
  {
    "lineNo": 11,
    "partNo": "A23-180",
    "qty": 400,
    "totalWeightLb": 212,
    "weightKg": 0.2404,
    "materialUsd": 4.87,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0279,
      "logisticsUsd": 0.2483,
      "dutyUsd": 0,
      "commissionUsd": 0.2163,
      "citUsd": 0.0433,
      "unitCostUsd": 5.4057,
      "ddpPriceUsd": 7.21,
      "ddpPriceVnd": 200000,
      "totalRevenueVnd": 80000000,
      "marginPerUnitUsd": 1.8,
      "marginPct": 25.02,
      "totalMarginUsd": 722,
      "totalCostUsd": 2162
    }
  },
  {
    "lineNo": 12,
    "partNo": "A23-180-B",
    "qty": 200,
    "totalWeightLb": 102,
    "weightKg": 0.2313,
    "materialUsd": 6.46,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0369,
      "logisticsUsd": 0.239,
      "dutyUsd": 0,
      "commissionUsd": 0.2832,
      "citUsd": 0.0566,
      "unitCostUsd": 7.0757,
      "ddpPriceUsd": 9.44,
      "ddpPriceVnd": 260000,
      "totalRevenueVnd": 52000000,
      "marginPerUnitUsd": 2.36,
      "marginPct": 25.05,
      "totalMarginUsd": 473,
      "totalCostUsd": 1415
    }
  },
  {
    "lineNo": 13,
    "partNo": "A23-169",
    "qty": 240,
    "totalWeightLb": 153.6,
    "weightKg": 0.2903,
    "materialUsd": 4.87,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0279,
      "logisticsUsd": 0.2999,
      "dutyUsd": 0,
      "commissionUsd": 0.2184,
      "citUsd": 0.0437,
      "unitCostUsd": 5.4598,
      "ddpPriceUsd": 7.28,
      "ddpPriceVnd": 200000,
      "totalRevenueVnd": 48000000,
      "marginPerUnitUsd": 1.82,
      "marginPct": 25,
      "totalMarginUsd": 437,
      "totalCostUsd": 1310
    }
  },
  {
    "lineNo": 14,
    "partNo": "A23-169-B",
    "qty": 120,
    "totalWeightLb": 76.8,
    "weightKg": 0.2903,
    "materialUsd": 5.01,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0287,
      "logisticsUsd": 0.2999,
      "dutyUsd": 0,
      "commissionUsd": 0.2244,
      "citUsd": 0.0449,
      "unitCostUsd": 5.6078,
      "ddpPriceUsd": 7.48,
      "ddpPriceVnd": 200000,
      "totalRevenueVnd": 24000000,
      "marginPerUnitUsd": 1.87,
      "marginPct": 25.03,
      "totalMarginUsd": 225,
      "totalCostUsd": 673
    }
  },
  {
    "lineNo": 15,
    "partNo": "A23-170",
    "qty": 240,
    "totalWeightLb": 76,
    "weightKg": 0.1436,
    "materialUsd": 4.37,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.025,
      "logisticsUsd": 0.1484,
      "dutyUsd": 0,
      "commissionUsd": 0.1911,
      "citUsd": 0.0382,
      "unitCostUsd": 4.7727,
      "ddpPriceUsd": 6.37,
      "ddpPriceVnd": 170000,
      "totalRevenueVnd": 40800000,
      "marginPerUnitUsd": 1.6,
      "marginPct": 25.08,
      "totalMarginUsd": 383,
      "totalCostUsd": 1145
    }
  },
  {
    "lineNo": 16,
    "partNo": "A23-170-B",
    "qty": 120,
    "totalWeightLb": 50.4,
    "weightKg": 0.1905,
    "materialUsd": 4.68,
    "dutyPct": 0,
    "expected": {
      "bankFeeUsd": 0.0268,
      "logisticsUsd": 0.1968,
      "dutyUsd": 0,
      "commissionUsd": 0.2061,
      "citUsd": 0.0412,
      "unitCostUsd": 5.1509,
      "ddpPriceUsd": 6.87,
      "ddpPriceVnd": 190000,
      "totalRevenueVnd": 22800000,
      "marginPerUnitUsd": 1.72,
      "marginPct": 25.02,
      "totalMarginUsd": 206,
      "totalCostUsd": 618
    }
  }
];

/** Excel TOTAL rows. */
export const AC0084_TOTALS = {
  air: {"qty":4080,"totalWeightLb":2273,"weightKg":1031.0328,"materialUsd":19271.2,"bankFeeUsd":110.2225,"logisticsUsd":4015,"dutyUsd":0,"commissionUsd":983.796,"citUsd":196.7592,"unitCostUsd":24576.9777,"ddpPriceUsd":32793.2,"totalRevenueVnd":890800000,"marginPct":25.05,"totalMarginUsd":8216,"totalCostUsd":24577},
  sea: {"qty":4080,"totalWeightLb":2273,"weightKg":1031.0328,"materialUsd":19271.2,"bankFeeUsd":110.2225,"logisticsUsd":1065,"dutyUsd":0,"commissionUsd":859.572,"citUsd":171.9144,"unitCostUsd":21477.9089,"ddpPriceUsd":28652.4,"totalRevenueVnd":778800000,"marginPct":25.04,"totalMarginUsd":7174,"totalCostUsd":21478},
} as const;
